class Tag:
    DEFAULT_FONT: str = "DEFAULT_FONT"
    MAIN_WINDOW: str = "MAIN_WINDOW"
    RESULT_TEXT: str = "RESULT_TEXT"
    HELP_WINDOW: str = "HELP_WINDOW"
    HELP_MENU_BUTTON: str = "HELP_MENU_BUTTON"

    LOAD_IMAGE_BUTTON: str = "LOAD_IMAGE_BUTTON"
    DETECT_TEXT_BUTTON: str = "DETECT_TEXT_BUTTON"
    COPY_TEXT_BUTTON: str = "COPY_TEXT_BUTTON"

    LOAD_IMAGE_TEXTURE: str = "LOAD_IMAGE_TEXTURE"
    DETECT_TEXT_TEXTURE: str = "DETECT_TEXT_TEXTURE"
    COPY_TEXT_TEXTURE: str = "COPY_TEXT_TEXTURE"

    LOADING_WINDOW: str = "LOADING_WINDOW"

    CURRENT_IMAGE_TEXTURE: str = "CURRENT_IMAGE_TEXTURE"
    CURRENT_IMAGE: str = "CURRENT_IMAGE"

    IMAGE_WINDOW: str = "IMAGE_WINDOW"

    THEME_RADIO_BUTTON: str = "THEME_RADIO_BUTTON"
